[package]
name = "destruction-studios/topbarplus-fork"
description = "Construct dynamic and intuitive topbar icons. Enhance the appearance and behaviour of these icons with features such as themes, dropdowns and menus."
license = "MPL2"
version = "3.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]